# AppVeyor CI settings (Windows Machine CI Tests)

environment:
  matrix:
    - PROFILE: "coding-conventions & docs"
      PYTHON_VERSION: "3.6"
      TOXENV: "docs,lint"
    - PROFILE: py27
      PYTHON_VERSION: "2.7"
      TOXENV: "py27,py27-datetime"
    - PROFILE: py35
      PYTHON_VERSION: "3.5"
      TOXENV: "py35,py35-datetime"
    - PROFILE: py36
      PYTHON_VERSION: "3.6"
      TOXENV: "py36,py36-datetime"
    - PROFILE: py37
      PYTHON_VERSION: "3.7"
      TOXENV: "py37,py37-datetime"


cache:
  - '%LOCALAPPDATA%\pip\Cache'

version: '{branch}.{build}'

install:
  - "python.exe -V"
  - "python.exe -m pip install tox"

build: off

test_script:
  - "python.exe -V"
  - "tox.exe"
